/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import { createInstance } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getApp = () => {
const appControllerGetHello = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/`, method: 'GET'
    },
      options);
    }
  return {appControllerGetHello}};
export type AppControllerGetHelloResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getApp>['appControllerGetHello']>>>
