/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateChatMessageDto,
  UpdateChatMessageDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getChatMessages = () => {
const chatMessagesControllerCreate = (
    createChatMessageDto: BodyType<CreateChatMessageDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/chat-messages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createChatMessageDto
    },
      options);
    }
  const chatMessagesControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/chat-messages`, method: 'GET'
    },
      options);
    }
  const chatMessagesControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/chat-messages/${id}`, method: 'GET'
    },
      options);
    }
  const chatMessagesControllerUpdate = (
    id: string,
    updateChatMessageDto: BodyType<UpdateChatMessageDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/chat-messages/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateChatMessageDto
    },
      options);
    }
  const chatMessagesControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/chat-messages/${id}`, method: 'DELETE'
    },
      options);
    }
  return {chatMessagesControllerCreate,chatMessagesControllerFindAll,chatMessagesControllerFindOne,chatMessagesControllerUpdate,chatMessagesControllerRemove}};
export type ChatMessagesControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getChatMessages>['chatMessagesControllerCreate']>>>
export type ChatMessagesControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getChatMessages>['chatMessagesControllerFindAll']>>>
export type ChatMessagesControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getChatMessages>['chatMessagesControllerFindOne']>>>
export type ChatMessagesControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getChatMessages>['chatMessagesControllerUpdate']>>>
export type ChatMessagesControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getChatMessages>['chatMessagesControllerRemove']>>>
