/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateGroupDto,
  UpdateGroupDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getGroups = () => {
const groupsControllerCreate = (
    createGroupDto: BodyType<CreateGroupDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/groups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createGroupDto
    },
      options);
    }
  const groupsControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/groups`, method: 'GET'
    },
      options);
    }
  const groupsControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/groups/${id}`, method: 'GET'
    },
      options);
    }
  const groupsControllerUpdate = (
    id: string,
    updateGroupDto: BodyType<UpdateGroupDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/groups/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateGroupDto
    },
      options);
    }
  const groupsControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/groups/${id}`, method: 'DELETE'
    },
      options);
    }
  return {groupsControllerCreate,groupsControllerFindAll,groupsControllerFindOne,groupsControllerUpdate,groupsControllerRemove}};
export type GroupsControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroups>['groupsControllerCreate']>>>
export type GroupsControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroups>['groupsControllerFindAll']>>>
export type GroupsControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroups>['groupsControllerFindOne']>>>
export type GroupsControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroups>['groupsControllerUpdate']>>>
export type GroupsControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroups>['groupsControllerRemove']>>>
