/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddGroupMemberDto,
  GroupMemberResponseDto,
  GroupMembersControllerRemoveMemberParams
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getGroupMembers = () => {
const groupMembersControllerAddMember = (
    addGroupMemberDto: BodyType<AddGroupMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<GroupMemberResponseDto>(
      {url: `/group-members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addGroupMemberDto
    },
      options);
    }
  /**
 * @summary Remove user from group
 */
const groupMembersControllerRemoveMember = (
    params: GroupMembersControllerRemoveMemberParams,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/group-members`, method: 'DELETE',
        params
    },
      options);
    }
  /**
 * @summary Get members of a group
 */
const groupMembersControllerGetGroupMembers = (
    groupId: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/group-members/group/${groupId}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary Get groups where user is a member
 */
const groupMembersControllerGetUserGroups = (
    userId: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/group-members/user/${userId}`, method: 'GET'
    },
      options);
    }
  return {groupMembersControllerAddMember,groupMembersControllerRemoveMember,groupMembersControllerGetGroupMembers,groupMembersControllerGetUserGroups}};
export type GroupMembersControllerAddMemberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroupMembers>['groupMembersControllerAddMember']>>>
export type GroupMembersControllerRemoveMemberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroupMembers>['groupMembersControllerRemoveMember']>>>
export type GroupMembersControllerGetGroupMembersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroupMembers>['groupMembersControllerGetGroupMembers']>>>
export type GroupMembersControllerGetUserGroupsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGroupMembers>['groupMembersControllerGetUserGroups']>>>
