/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSubscriptionDto,
  GetSubscriptionDto,
  Subscription,
  UpdateSubscriptionDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSubscription = () => {
/**
 * @summary create subscription
 */
const subscriptionControllerCreate = (
    createSubscriptionDto: BodyType<CreateSubscriptionDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<Subscription>(
      {url: `/subscriptions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSubscriptionDto
    },
      options);
    }
  /**
 * @summary get all subscriptions
 */
const subscriptionControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<Subscription[]>(
      {url: `/subscriptions`, method: 'GET'
    },
      options);
    }
  /**
 * @summary get subscription
 */
const subscriptionControllerFindOne = (
    id: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<GetSubscriptionDto>(
      {url: `/subscriptions/${id}`, method: 'GET'
    },
      options);
    }
  /**
 * @summary update subscription
 */
const subscriptionControllerUpdate = (
    id: string,
    updateSubscriptionDto: BodyType<UpdateSubscriptionDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<Subscription>(
      {url: `/subscriptions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSubscriptionDto
    },
      options);
    }
  /**
 * @summary delete subscription
 */
const subscriptionControllerRemove = (
    id: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/${id}`, method: 'DELETE'
    },
      options);
    }
  return {subscriptionControllerCreate,subscriptionControllerFindAll,subscriptionControllerFindOne,subscriptionControllerUpdate,subscriptionControllerRemove}};
export type SubscriptionControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerCreate']>>>
export type SubscriptionControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerFindAll']>>>
export type SubscriptionControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerFindOne']>>>
export type SubscriptionControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerUpdate']>>>
export type SubscriptionControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerRemove']>>>
