/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSubscriptionDto,
  UpdateSubscriptionDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSubscriptions = () => {
const subscriptionsControllerCreate = (
    createSubscriptionDto: BodyType<CreateSubscriptionDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSubscriptionDto
    },
      options);
    }
  const subscriptionsControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions`, method: 'GET'
    },
      options);
    }
  const subscriptionsControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/${id}`, method: 'GET'
    },
      options);
    }
  const subscriptionsControllerUpdate = (
    id: string,
    updateSubscriptionDto: BodyType<UpdateSubscriptionDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSubscriptionDto
    },
      options);
    }
  const subscriptionsControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/${id}`, method: 'DELETE'
    },
      options);
    }
  return {subscriptionsControllerCreate,subscriptionsControllerFindAll,subscriptionsControllerFindOne,subscriptionsControllerUpdate,subscriptionsControllerRemove}};
export type SubscriptionsControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptions>['subscriptionsControllerCreate']>>>
export type SubscriptionsControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptions>['subscriptionsControllerFindAll']>>>
export type SubscriptionsControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptions>['subscriptionsControllerFindOne']>>>
export type SubscriptionsControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptions>['subscriptionsControllerUpdate']>>>
export type SubscriptionsControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptions>['subscriptionsControllerRemove']>>>
