/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSubscriptionDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSubscriptionAdmin = () => {
const subscriptionAdminControllerCreateSubscription = (
    createSubscriptionDto: BodyType<CreateSubscriptionDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/admin/subscriptions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSubscriptionDto
    },
      options);
    }
  const subscriptionAdminControllerGetAllSubscriptions = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/admin/subscriptions`, method: 'GET'
    },
      options);
    }
  const subscriptionAdminControllerGetSubscriptionById = (
    id: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/admin/subscriptions/${id}`, method: 'GET'
    },
      options);
    }
  return {subscriptionAdminControllerCreateSubscription,subscriptionAdminControllerGetAllSubscriptions,subscriptionAdminControllerGetSubscriptionById}};
export type SubscriptionAdminControllerCreateSubscriptionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionAdmin>['subscriptionAdminControllerCreateSubscription']>>>
export type SubscriptionAdminControllerGetAllSubscriptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionAdmin>['subscriptionAdminControllerGetAllSubscriptions']>>>
export type SubscriptionAdminControllerGetSubscriptionByIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionAdmin>['subscriptionAdminControllerGetSubscriptionById']>>>
