/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSubscriptionMemberDto,
  UpdateSubscriptionMemberDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSubscriptionMembers = () => {
const subscriptionMembersControllerCreate = (
    createSubscriptionMemberDto: BodyType<CreateSubscriptionMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSubscriptionMemberDto
    },
      options);
    }
  const subscriptionMembersControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-members`, method: 'GET'
    },
      options);
    }
  const subscriptionMembersControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-members/${id}`, method: 'GET'
    },
      options);
    }
  const subscriptionMembersControllerUpdate = (
    id: string,
    updateSubscriptionMemberDto: BodyType<UpdateSubscriptionMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-members/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSubscriptionMemberDto
    },
      options);
    }
  const subscriptionMembersControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-members/${id}`, method: 'DELETE'
    },
      options);
    }
  return {subscriptionMembersControllerCreate,subscriptionMembersControllerFindAll,subscriptionMembersControllerFindOne,subscriptionMembersControllerUpdate,subscriptionMembersControllerRemove}};
export type SubscriptionMembersControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerCreate']>>>
export type SubscriptionMembersControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerFindAll']>>>
export type SubscriptionMembersControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerFindOne']>>>
export type SubscriptionMembersControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerUpdate']>>>
export type SubscriptionMembersControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerRemove']>>>
