/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddSubscriptionMemberDto,
  RemoveSubscriptionMemberDto,
  SubscriptionMember
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSubscriptionMembers = () => {
const subscriptionMembersControllerAddMember = (
    subscriptionId: number,
    addSubscriptionMemberDto: BodyType<AddSubscriptionMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-members/${subscriptionId}/add-member`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addSubscriptionMemberDto
    },
      options);
    }
  const subscriptionMembersControllerFindAll = (
    id: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<SubscriptionMember[]>(
      {url: `/subscription-members/${id}`, method: 'GET'
    },
      options);
    }
  const subscriptionMembersControllerRemoveMember = (
    memberId: number,
    removeSubscriptionMemberDto: BodyType<RemoveSubscriptionMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-members/${memberId}`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: removeSubscriptionMemberDto
    },
      options);
    }
  return {subscriptionMembersControllerAddMember,subscriptionMembersControllerFindAll,subscriptionMembersControllerRemoveMember}};
export type SubscriptionMembersControllerAddMemberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerAddMember']>>>
export type SubscriptionMembersControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerFindAll']>>>
export type SubscriptionMembersControllerRemoveMemberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMembers>['subscriptionMembersControllerRemoveMember']>>>
