/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddMemberDto,
  CreateSubscriptionDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSubscription = () => {
const subscriptionControllerCreateSubscription = (
    createSubscriptionDto: BodyType<CreateSubscriptionDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSubscriptionDto
    },
      options);
    }
  const subscriptionControllerAddMember = (
    id: number,
    addMemberDto: BodyType<AddMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/${id}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addMemberDto
    },
      options);
    }
  const subscriptionControllerGetMembers = (
    id: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/${id}/members`, method: 'GET'
    },
      options);
    }
  const subscriptionControllerRemoveMember = (
    id: number,
    userId: number,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/${id}/members/${userId}`, method: 'DELETE'
    },
      options);
    }
  const subscriptionControllerDeactivateExpiredSubscriptions = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscriptions/deactivate`, method: 'PATCH'
    },
      options);
    }
  return {subscriptionControllerCreateSubscription,subscriptionControllerAddMember,subscriptionControllerGetMembers,subscriptionControllerRemoveMember,subscriptionControllerDeactivateExpiredSubscriptions}};
export type SubscriptionControllerCreateSubscriptionResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerCreateSubscription']>>>
export type SubscriptionControllerAddMemberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerAddMember']>>>
export type SubscriptionControllerGetMembersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerGetMembers']>>>
export type SubscriptionControllerRemoveMemberResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerRemoveMember']>>>
export type SubscriptionControllerDeactivateExpiredSubscriptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscription>['subscriptionControllerDeactivateExpiredSubscriptions']>>>
