/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSubscriptionMemberDto,
  UpdateSubscriptionMemberDto
} from './models';

import { createInstance } from '../api-instance';
import type { BodyType } from '../api-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSubscriptionMember = () => {
const subscriptionMemberControllerCreate = (
    createSubscriptionMemberDto: BodyType<CreateSubscriptionMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-member`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createSubscriptionMemberDto
    },
      options);
    }
  const subscriptionMemberControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-member`, method: 'GET'
    },
      options);
    }
  const subscriptionMemberControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-member/${id}`, method: 'GET'
    },
      options);
    }
  const subscriptionMemberControllerUpdate = (
    id: string,
    updateSubscriptionMemberDto: BodyType<UpdateSubscriptionMemberDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-member/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSubscriptionMemberDto
    },
      options);
    }
  const subscriptionMemberControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/subscription-member/${id}`, method: 'DELETE'
    },
      options);
    }
  return {subscriptionMemberControllerCreate,subscriptionMemberControllerFindAll,subscriptionMemberControllerFindOne,subscriptionMemberControllerUpdate,subscriptionMemberControllerRemove}};
export type SubscriptionMemberControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMember>['subscriptionMemberControllerCreate']>>>
export type SubscriptionMemberControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMember>['subscriptionMemberControllerFindAll']>>>
export type SubscriptionMemberControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMember>['subscriptionMemberControllerFindOne']>>>
export type SubscriptionMemberControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMember>['subscriptionMemberControllerUpdate']>>>
export type SubscriptionMemberControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSubscriptionMember>['subscriptionMemberControllerRemove']>>>
