/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import { createInstance } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTransactions = () => {
const transactionsControllerGetTransactions = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/wallet/transactions`, method: 'GET'
    },
      options);
    }
  return {transactionsControllerGetTransactions}};
export type TransactionsControllerGetTransactionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTransactions>['transactionsControllerGetTransactions']>>>
