/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type {
  Transaction
} from './models';

import { createInstance } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTransactions = () => {
const transactionsControllerGetTransactions = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<Transaction[]>(
      {url: `/wallet/transactions/${id}`, method: 'GET'
    },
      options);
    }
  return {transactionsControllerGetTransactions}};
export type TransactionsControllerGetTransactionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTransactions>['transactionsControllerGetTransactions']>>>
