/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  UpdateUserDto
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUsers = () => {
const usersControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/users`, method: 'GET'
    },
      options);
    }
  const usersControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/users/${id}`, method: 'GET'
    },
      options);
    }
  const usersControllerUpdate = (
    id: string,
    updateUserDto: BodyType<UpdateUserDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/users/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      options);
    }
  const usersControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/users/${id}`, method: 'DELETE'
    },
      options);
    }
  return {usersControllerFindAll,usersControllerFindOne,usersControllerUpdate,usersControllerRemove}};
export type UsersControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerFindAll']>>>
export type UsersControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerFindOne']>>>
export type UsersControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerUpdate']>>>
export type UsersControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerRemove']>>>
