/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetUserDto,
  SearchUserResponseDto,
  UpdateUserDto,
  UsersControllerSearchUsersParams
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUsers = () => {
const usersControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/users`, method: 'GET'
    },
      options);
    }
  const usersControllerSearchUsers = (
    params: UsersControllerSearchUsersParams,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<SearchUserResponseDto[]>(
      {url: `/users/search`, method: 'GET',
        params
    },
      options);
    }
  const usersControllerGetProfile = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<GetUserDto>(
      {url: `/users/profile/${id}`, method: 'GET'
    },
      options);
    }
  const usersControllerUpdate = (
    id: string,
    updateUserDto: BodyType<UpdateUserDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/users/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      options);
    }
  const usersControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/users/${id}`, method: 'DELETE'
    },
      options);
    }
  return {usersControllerFindAll,usersControllerSearchUsers,usersControllerGetProfile,usersControllerUpdate,usersControllerRemove}};
export type UsersControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerFindAll']>>>
export type UsersControllerSearchUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerSearchUsers']>>>
export type UsersControllerGetProfileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerGetProfile']>>>
export type UsersControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerUpdate']>>>
export type UsersControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersControllerRemove']>>>
