/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type {
  DepositDto,
  Wallet
} from './models';

import { createInstance } from '../custom-instance';
import type { BodyType } from '../custom-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getWallet = () => {
const walletControllerDeposit = (
    depositDto: BodyType<DepositDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<Wallet>(
      {url: `/wallet/deposit`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: depositDto
    },
      options);
    }
  const walletControllerGetBalance = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<Wallet>(
      {url: `/wallet`, method: 'GET'
    },
      options);
    }
  const walletControllerGetTransactions = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/wallet/transactions`, method: 'GET'
    },
      options);
    }
  return {walletControllerDeposit,walletControllerGetBalance,walletControllerGetTransactions}};
export type WalletControllerDepositResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerDeposit']>>>
export type WalletControllerGetBalanceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerGetBalance']>>>
export type WalletControllerGetTransactionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerGetTransactions']>>>
