/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateWalletDto,
  UpdateWalletDto
} from './models';

import { createInstance } from '../api-instance';
import type { BodyType } from '../api-instance';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getWallet = () => {
const walletControllerCreate = (
    createWalletDto: BodyType<CreateWalletDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/wallet`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createWalletDto
    },
      options);
    }
  const walletControllerFindAll = (
    
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/wallet`, method: 'GET'
    },
      options);
    }
  const walletControllerFindOne = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/wallet/${id}`, method: 'GET'
    },
      options);
    }
  const walletControllerUpdate = (
    id: string,
    updateWalletDto: BodyType<UpdateWalletDto>,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/wallet/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateWalletDto
    },
      options);
    }
  const walletControllerRemove = (
    id: string,
 options?: SecondParameter<typeof createInstance>,) => {
      return createInstance<void>(
      {url: `/wallet/${id}`, method: 'DELETE'
    },
      options);
    }
  return {walletControllerCreate,walletControllerFindAll,walletControllerFindOne,walletControllerUpdate,walletControllerRemove}};
export type WalletControllerCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerCreate']>>>
export type WalletControllerFindAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerFindAll']>>>
export type WalletControllerFindOneResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerFindOne']>>>
export type WalletControllerUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerUpdate']>>>
export type WalletControllerRemoveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWallet>['walletControllerRemove']>>>
