openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /users:
    get:
      operationId: UsersController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Users
  /users/{id}:
    get:
      operationId: UsersController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Users
    patch:
      operationId: UsersController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDto'
      responses:
        '200':
          description: ''
      tags:
        - Users
    delete:
      operationId: UsersController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Users
  /wallet/deposit:
    post:
      operationId: WalletController_deposit
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositDto'
      responses:
        '201':
          description: ''
      tags:
        - Wallet
  /wallet:
    get:
      operationId: WalletController_getBalance
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Wallet
  /wallet/transactions:
    get:
      operationId: TransactionsController_getTransactions
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Transactions
  /subscriptions:
    post:
      operationId: SubscriptionController_createSubscription
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionDto'
      responses:
        '201':
          description: ''
      tags:
        - Subscription
  /subscriptions/{id}/members:
    post:
      operationId: SubscriptionController_addMember
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMemberDto'
      responses:
        '201':
          description: ''
      tags:
        - Subscription
    get:
      operationId: SubscriptionController_getMembers
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Subscription
  /subscriptions/{id}/members/{userId}:
    delete:
      operationId: SubscriptionController_removeMember
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
        - name: userId
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - Subscription
  /subscriptions/deactivate:
    patch:
      operationId: SubscriptionController_deactivateExpiredSubscriptions
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Subscription
  /subscription-members:
    post:
      operationId: SubscriptionMembersController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionMemberDto'
      responses:
        '201':
          description: ''
      tags:
        - SubscriptionMembers
    get:
      operationId: SubscriptionMembersController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - SubscriptionMembers
  /subscription-members/{id}:
    get:
      operationId: SubscriptionMembersController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - SubscriptionMembers
    patch:
      operationId: SubscriptionMembersController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriptionMemberDto'
      responses:
        '200':
          description: ''
      tags:
        - SubscriptionMembers
    delete:
      operationId: SubscriptionMembersController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - SubscriptionMembers
  /auth/signUp:
    post:
      operationId: AuthController_SignUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpAuth_DTO'
      responses:
        '201':
          description: ''
      tags:
        - Auth
  /auth/signIn:
    post:
      operationId: AuthController_SignIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInAuth_DTO'
      responses:
        '200':
          description: Sign in successful
      tags:
        - Auth
  /auth/google:
    get:
      operationId: AuthController_googleLogin
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /auth/google/redirect:
    get:
      operationId: AuthController_googleRedirect
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /auth/session:
    get:
      operationId: AuthController_getSessionInfo
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSessionInfoDto'
      tags:
        - Auth
  /chat-messages:
    post:
      operationId: ChatMessagesController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChatMessageDto'
      responses:
        '201':
          description: ''
      tags:
        - ChatMessages
    get:
      operationId: ChatMessagesController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - ChatMessages
  /chat-messages/{id}:
    get:
      operationId: ChatMessagesController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - ChatMessages
    patch:
      operationId: ChatMessagesController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChatMessageDto'
      responses:
        '200':
          description: ''
      tags:
        - ChatMessages
    delete:
      operationId: ChatMessagesController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - ChatMessages
  /groups:
    post:
      operationId: GroupsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGroupDto'
      responses:
        '201':
          description: ''
      tags:
        - Groups
    get:
      operationId: GroupsController_findAll
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Groups
  /groups/{id}:
    get:
      operationId: GroupsController_findOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Groups
    patch:
      operationId: GroupsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGroupDto'
      responses:
        '200':
          description: ''
      tags:
        - Groups
    delete:
      operationId: GroupsController_remove
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Groups
  /admin/subscriptions:
    post:
      operationId: SubscriptionAdminController_createSubscription
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSubscriptionDto'
      responses:
        '201':
          description: ''
      tags:
        - SubscriptionAdmin
    get:
      operationId: SubscriptionAdminController_getAllSubscriptions
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - SubscriptionAdmin
  /admin/subscriptions/{id}:
    get:
      operationId: SubscriptionAdminController_getSubscriptionById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: ''
      tags:
        - SubscriptionAdmin
info:
  title: AI manager
  description: ''
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    UpdateUserDto:
      type: object
      properties: {}
    DepositDto:
      type: object
      properties: {}
    CreateSubscriptionDto:
      type: object
      properties:
        serviceName:
          type: string
          example: Chat gpt
        price:
          type: number
          example: 10
        description:
          type: string
          example: Chat gpt description
        expiresAt:
          format: date-time
          type: string
          example: '2023-10-10T00:00:00Z'
      required:
        - serviceName
        - price
        - description
        - expiresAt
    AddMemberDto:
      type: object
      properties: {}
    CreateSubscriptionMemberDto:
      type: object
      properties: {}
    UpdateSubscriptionMemberDto:
      type: object
      properties: {}
    SignUpAuth_DTO:
      type: object
      properties:
        email:
          type: string
          example: example@gmail.com
          description: Email
        password:
          type: string
          example: password
          description: Password
      required:
        - email
        - password
    SignInAuth_DTO:
      type: object
      properties:
        email:
          type: string
          example: example@gmail.com
          description: Email
      required:
        - email
    GetSessionInfoDto:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
        iat:
          type: number
        exp:
          type: number
      required:
        - id
        - email
        - iat
        - exp
    CreateChatMessageDto:
      type: object
      properties: {}
    UpdateChatMessageDto:
      type: object
      properties: {}
    CreateGroupDto:
      type: object
      properties: {}
    UpdateGroupDto:
      type: object
      properties: {}
