version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432" # Этот порт открыт для подключения к базе данных
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80" # Порт, на котором доступен pgAdmin
    networks:
      - postgres-network
    depends_on:
      - db

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge
