/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export interface AddGroupMemberDto {
  /** ID группы */
  groupId: number;
  /** ID пользователя */
  userId: number;
  /** Является ли админом */
  isAdmin?: boolean;
}
