/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export type CreateSubscriptionDtoType = typeof CreateSubscriptionDtoType[keyof typeof CreateSubscriptionDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateSubscriptionDtoType = {
  personal: 'personal',
  group: 'group',
  trial: 'trial',
} as const;
