/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSubscriptionDtoCurrency } from './createSubscriptionDtoCurrency';
import type { CreateSubscriptionDtoType } from './createSubscriptionDtoType';

export interface CreateSubscriptionDto {
  serviceName: string;
  price: number;
  currency: CreateSubscriptionDtoCurrency;
  description?: string;
  startsAt: string;
  expiresAt: string;
  type: CreateSubscriptionDtoType;
}
