/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * AI manager
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSubscriptionDto {
  serviceName: string;
  price: number;
  description: string;
  expiresAt: string;
}
