/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of the subscription
 */
export type GetSubscriptionDtoType = typeof GetSubscriptionDtoType[keyof typeof GetSubscriptionDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSubscriptionDtoType = {
  personal: 'personal',
  group: 'group',
  trial: 'trial',
} as const;
