/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type { Group } from './group';

/**
 * Group associated with the subscription (if any)
 * @nullable
 */
export type GetSubscriptionDtoGroup = Group | null;
