/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserDtoPreferences } from './getUserDtoPreferences';

export interface GetUserDto {
  id: number;
  email: string;
  isEmailVerified: boolean;
  profilePicture: string;
  fullName: string;
  bio: string;
  role: string;
  preferences: GetUserDtoPreferences;
  createdAt: string;
  updatedAt: string;
}
