/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export interface GroupMemberResponseDto {
  /** ID записи участника */
  id: number;
  /** ID пользователя */
  userId: number;
  /** Email участника */
  email: string;
  /** Имя участника */
  fullName?: string;
  /** Является ли админом */
  isAdmin: boolean;
  /** Когда добавлен */
  joinedAt: string;
}
