/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export interface SearchUserResponseDto {
  /** User ID */
  id: number;
  /** User Email */
  email: string;
  /** Email Verified Status */
  isEmailVerified: boolean;
  /** Profile Picture URL */
  profilePicture: string;
}
