/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

/**
 * Currency of the subscription
 */
export type SubscriptionCurrency = typeof SubscriptionCurrency[keyof typeof SubscriptionCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionCurrency = {
  USD: 'USD',
  EUR: 'EUR',
  RUB: 'RUB',
  UAH: 'UAH',
  KGS: 'KGS',
} as const;
