/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

/**
 * Тип транзакции
 */
export type TransactionType = typeof TransactionType[keyof typeof TransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionType = {
  deposit: 'deposit',
  withdraw: 'withdraw',
} as const;
