/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionType } from './transactionType';
import type { Wallet } from './wallet';
import type { User } from './user';

export interface Transaction {
  /** Уникальный идентификатор транзакции */
  id: number;
  /** Сумма транзакции */
  amount: number;
  /** Тип транзакции */
  type: TransactionType;
  /** Описание транзакции */
  description?: string;
  /** Дата создания транзакции */
  createdAt: string;
  /** Кошелек, к которому относится транзакция */
  wallet: Wallet;
  /** Пользователь, совершивший транзакцию */
  user: User;
}
