/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSubscriptionDtoType = typeof UpdateSubscriptionDtoType[keyof typeof UpdateSubscriptionDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSubscriptionDtoType = {
  personal: 'personal',
  group: 'group',
  trial: 'trial',
} as const;
