/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserDto {
  /** The full name of the user */
  fullName: string;
  /** The bio of the user */
  bio: string;
  /** The profile picture URL of the user */
  profilePicture: string;
}
