/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSubscriptionDtoCurrency } from './updateSubscriptionDtoCurrency';
import type { UpdateSubscriptionDtoType } from './updateSubscriptionDtoType';

export interface UpdateSubscriptionDto {
  serviceName: string;
  price: number;
  currency: UpdateSubscriptionDtoCurrency;
  description?: string;
  startsAt: string;
  expiresAt: string;
  type: UpdateSubscriptionDtoType;
}
