/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSubscriptionDtoCurrency = typeof UpdateSubscriptionDtoCurrency[keyof typeof UpdateSubscriptionDtoCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSubscriptionDtoCurrency = {
  USD: 'USD',
  EUR: 'EUR',
  RUB: 'RUB',
  UAH: 'UAH',
  KGS: 'KGS',
} as const;
