/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */
import type { UserPreferences } from './userPreferences';
import type { Wallet } from './wallet';
import type { Subscription } from './subscription';
import type { SubscriptionMember } from './subscriptionMember';
import type { Transaction } from './transaction';
import type { ChatMessage } from './chatMessage';
import type { Group } from './group';

export interface User {
  /** User ID */
  id: number;
  /** Email */
  email: string;
  /** Password hash */
  passwordHash: string;
  /** Salt */
  salt: string;
  /** Email verified */
  isEmailVerified: boolean;
  /** Avatar URL */
  profilePicture?: string;
  /** Name */
  fullName?: string;
  /** Bio */
  bio?: string;
  /** Role */
  role: string;
  /** Prefs */
  preferences?: UserPreferences;
  /** Created at */
  createdAt: string;
  /** Updated at */
  updatedAt: string;
  /** Wallet */
  wallet: Wallet;
  /** Owner of subscriptions */
  subscriptions: Subscription[];
  /** Member of subscriptions */
  subscriptionMembers: SubscriptionMember[];
  /** Transactions */
  transactions: Transaction[];
  /** Messages */
  chatMessages: ChatMessage[];
  /** Owned groups */
  x: Group[];
  /** Joined groups */
  groupMemberships: Group[];
}
