/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * AI manager
 * хуйня
 * OpenAPI spec version: 1.0.0
 */

export interface Wallet {
  id: number;
  balance: number;
  updatedAt: string;
  createdAt: string;
}
