// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

import { AppThemeProvider, Providers } from './_provider';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body>
        <Providers>
          <AppThemeProvider>{children}</AppThemeProvider>
        </Providers>
      </body>
    </html>
  );
}

